name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        TEMPLATE_ID_EMAIL_PAYMENT_CONFIRM: ${{ secrets.TEMPLATE_ID_EMAIL_PAYMENT_CONFIRM }}
        TEMPLATE_ID_SMS_PAYMENT_CONFIRM: ${{ secrets.TEMPLATE_ID_SMS_PAYMENT_CONFIRM }}
        TEMPLATE_ID_EMAIL_APPLY_CONFIRM: ${{ secrets.TEMPLATE_ID_EMAIL_APPLY_CONFIRM }}
        TEMPLATE_ID_SMS_APPLY_CONFIRM: ${{ secrets.TEMPLATE_ID_SMS_APPLY_CONFIRM }}
    - name: npm lint
      run: |
        npm run lint
      env:
        CI: true
